Bank/Models/Contact.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Bank.Models
{
    public class Contact
    {
        public int ContactId { get; set; }

        // user ID from AspNetUser table.
        public string OwnerID { get; set; }

        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        public ContactStatus Status { get; set; }
    }

    public enum ContactStatus
    {
        Submitted,
        Approved,
        Rejected
    }
}

Bank/ViewModels/Login.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Bank.ViewModels
{
    public class Login
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public bool RememberMe { get; set; }

    }
}

Bank/Pages/About.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bank.Pages
{
    public class AboutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Bank/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Bank.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Bank/Pages/FAQ.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bank.Pages
{
    public class FAQModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Bank/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bank.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

Bank/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bank.Models;
using Bank.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bank.Pages
{
    public class LoginModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly BankDbContext context;

        [BindProperty]
        public Login  Model { get; set; }
        public ApplicationUser MyUser { get; private set; }

        public LoginModel(SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager, BankDbContext context)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
            this.context = context;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync(string returnurl = null)
        {
            if (ModelState.IsValid)
            {
                var IdentityResult = await signInManager.PasswordSignInAsync(Model.Email, Model.Password, Model.RememberMe, false);
                if (IdentityResult.Succeeded)
                {

                    MyUser = userManager.Users.FirstOrDefault(m => m.Email == Model.Email);

                    if (await userManager.IsInRoleAsync(MyUser, "Admin"))
                    {
                        if (returnurl == null || returnurl == "/")
                        {                          

                            return RedirectToPage("Index");
                        }
                        else
                        {
                            return RedirectToPage(returnurl);
                        }
                    }
                    else
                    {
                        if (returnurl == null || returnurl == "/")
                        {                           
                            return RedirectToPage("Account/Dashboard");
                        }
                        else
                        {
                            return RedirectToPage(returnurl);
                        }
                    }



                }
                ModelState.AddModelError("", "Username or Password is incorrect");
            }
            return Page();
        }
    }
}

Bank/Pages/Logout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Bank.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bank.Pages.Account
{
    public class LogoutModel : PageModel
    {
        private readonly SignInManager<ApplicationUser> signInManager;

        public LogoutModel(SignInManager<ApplicationUser> signInManager)
        {
            this.signInManager = signInManager;
        }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostLogoutAsync()
        {
            await signInManager.SignOutAsync();
            return RedirectToPage("Login");
        }

        public  IActionResult OnPostDontLogoutAsync()
        {
           
            return RedirectToPage("Index");
        }
    }
}

Bank/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bank.Pages
{
    
    public class PrivacyModel : PageModel
    {
        
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Bank/Pages/Register.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Threading.Tasks;
using Bank.Models;
using Bank.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bank.Pages
{

    public class Number
    {
        private readonly Random _random = new Random();
        public string InitialNumber()
        {
            var idBuilder = new StringBuilder();


            int itti = 200;
            // contant account number initial  
            idBuilder.Append(itti);

            // 8-Digits between 1000 and 9999  
            idBuilder.Append(RandomNumber(10000000, 99999999));


            return idBuilder.ToString();
        }

        public int RandomNumber(int min, int max)
        {
            return _random.Next(min, max);
        }

    }
    public class RegisterModel : PageModel
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly BankDbContext context;

        public RegisterModel(UserManager<ApplicationUser>userManager, SignInManager<ApplicationUser> signInManager, RoleManager<IdentityRole> roleManager, BankDbContext context)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.roleManager = roleManager;
            this.context = context;

        }

        [BindProperty]
        public Register Model { get; set; }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if(ModelState.IsValid)
            {
                var firstAccount = userManager.Users.Count() == 0;
                var roleaccount = roleManager.Roles.Count() == 0;
                if(roleaccount)
                {
                    IdentityRole identityRole = new IdentityRole { Name = "Admin" };
                    IdentityRole identityRole1 = new IdentityRole { Name = "User" };

                    await roleManager.CreateAsync(identityRole);
                    await roleManager.CreateAsync(identityRole1);
                    
                }
                
               

                var user = new ApplicationUser()
                {
                    
                    UserName = Model.Email,
                    Email = Model.Email,
                    FirstName = Model.FirstName,
                    LastName = Model.LastName,
                    MarriageStatus = Model.MarriageStatus,
                    Gender = Model.Gender,
                    Occupation = Model.Occupation,
                    Address = Model.Address,
                    State = Model.State,
                    Country = Model.Country,
                    PhoneNumber = Model.PhoneNumber,
                    AccountStatus = "Approved",
                    AccountType = Model.AccountType,
                    Created = DateTime.Now,



                };
                //Account Number generator 
                var generator = new Number();
                string account = generator.InitialNumber();

                //// Retrieve the Name of HOST
                //string hostName = Dns.GetHostName();
                //Console.WriteLine("Host Name is(Your Computer Name): {0}", hostName);

                //// Get the Local IP Address
                //string myIP = Dns.GetHostByName(hostName).AddressList[0].ToString();

                var profile = new Profile()
                {
                    Balance = 0,
                    
                    AccountNo = account,
                    CardNo = "423"+ account,
                    CVV = "204",
                    CardExpireDate ="12/26",
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    Email = user.Email, 
                    Status = "Approved",
                    
                };
               
                
               var result = await userManager.CreateAsync(user, Model.Password);
                if (result.Succeeded)
                {
                    context.Add(profile);
                    await context.SaveChangesAsync();
                    if (firstAccount)
                    {
                        await userManager.AddToRoleAsync(user, "Admin");
                    }
                    else
                    {
                        await userManager.AddToRoleAsync(user, "User");
                    }


                    try
                    {
                        StreamReader bd = new(@"~\NewBank\Bank\Pages\mailbody.html");
                        var credentials = new NetworkCredential("test@test.com", "Money2018$");
                        var mail1 = new MailMessage();
                        //var mail2 = new MailMessage();
                        var client = new SmtpClient();
                        string Email = user.Email;
                        string Message = "Thank you for Signing Up." + "</br>"  + " Your Account is Under Review, Please Contact Customer Service on customer-support@bankplc.com for more information";
                        string name = user.FirstName;
                        // sed Mail
                        //sender  body
                        string Mailtext1 = bd.ReadToEnd();
                        Mailtext1 = Mailtext1.Replace("{name}", name);
                        Mailtext1 = Mailtext1.Replace("{message}", Message);
                        Mailtext1 = Mailtext1.Replace("{subject}", "Signup Notification from The bank Plc");
                        //mail to sender 
                        mail1 = new MailMessage()
                        {
                            From = new MailAddress("customer-support@bankplc.com", "Your bank Name"),
                            Subject = "Signup Notification from The bank Plc",
                            Body = Mailtext1
                        };
                        mail1.IsBodyHtml = true;
                        mail1.To.Add(new MailAddress(Email));
                        //smtp config
                        client = new SmtpClient()
                        {
                            Port = 8889,
                            DeliveryMethod = SmtpDeliveryMethod.Network,
                            UseDefaultCredentials = false,
                            Host = "mail5013.site4now.net",
                            EnableSsl = false,
                            Credentials = credentials,
                            Timeout = 100
                        };
                        client.Send(mail1);                    
                    }
                    catch (Exception e)
                    {
                        Console.Write(e);
                    }
                    // sed Mail
                    //string Message = "Thank you for Signing Up."  + "\n " +  " Your Account is Under Review, Please Contact Customer Service on customer-support@bankplc.com for more information";
                    //string subject = "Signup Notification from The bank Plc";
                    //string Email = user.Email;
                    //string name = user.FirstName;

                    //StreamReader bd = new (@"C:\Projects\NewBank\Bank\Pages\mailbody.html");

                    //string Mailtext = bd.ReadToEnd();
                    //Mailtext = Mailtext.Replace("{name}", name);
                    //Mailtext = Mailtext.Replace("{message}", Message);
                    //Mailtext = Mailtext.Replace("{subject}", subject);

                    //// Credentials
                    //var credentials = new NetworkCredential("customer-support@bankplc.com", "Money2018$");

                    // Mail message
                    //var mail = new MailMessage()
                    //{
                    //    From = new MailAddress("customer-support@bankplc.com", " Your bank Name"),
                    //    Subject = subject,
                    //    Body = Mailtext
                    //};

                    //mail.IsBodyHtml = true;
                    //mail.To.Add(new MailAddress(Email));

                    // Smtp client
                    //var client = new SmtpClient()
                    //{
                    //    Port = 8889,
                    //    DeliveryMethod = SmtpDeliveryMethod.Network,
                    //    UseDefaultCredentials = false,
                    //    Host = "mail5013.site4now.net",
                    //    EnableSsl = false,
                    //    Credentials = credentials,
                    //    Timeout=100
                    //};

                    //client.Send(mail); // Send the mail

                    //await signInManager.SignInAsync(user, false);
                    return RedirectToPage("Login");
                }
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }

            }
            return Page();
        }
    }
}

Bank/Pages/Reviews.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bank.Pages
{
    public class ReviewsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Bank/Pages/Team.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bank.Pages
{
    public class TeamModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Bank/Pages/Update.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Bank.Pages
{
    public class UpdateModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Bank/Pages/About.cshtml
@page
@model Bank.Pages.AboutModel
@{
}

<!-- Start breadcrumbs area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb text-center">
                    <div class="section-headline white-headline text-center">
                        <h3>About Us</h3>
                    </div>
                    <ul>
                        <li class="home-bread">Home</li>
                        <li>About us</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcrumbs area -->
<!-- Start How to area -->
<div class="how-to-area bg-color area-padding">
    <div class="container">
        <div class="row">
            <div class="all-services">
                <!-- Start single column-->
                <div class="col-md-4 col-sm-4 col-xs-12">
                    <div class="well-services">
                        <div class="well-img">
                            <a class="big-icon" href="#"><i class="flaticon-102-businessman"></i></a>
                        </div>
                        <div class="main-wel">
                            <div class="wel-content">
                                <h4>Create an account</h4>
                                <p> Don't have account with us? what are you still waiting for.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End single column-->
                <!-- Start single column-->
                <div class="col-md-4 col-sm-4 col-xs-12">
                    <div class="well-services ">
                        <div class="well-img">
                            <a class="big-icon" href="#"><i class="flaticon-046-bank-1"></i></a>
                        </div>
                        <div class="main-wel">
                            <div class="wel-content">
                                <h4>Attach other bank cards</h4>
                                <p>You can also link your other bank cards to send money from.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End single column-->
                <!-- Start single column-->
                <div class="col-md-4 col-sm-4 col-xs-12">
                    <div class="well-services">
                        <div class="well-img">
                            <a class="big-icon" href="#"><i class="flaticon-028-money"></i></a>
                        </div>
                        <div class="main-wel">
                            <div class="wel-content">
                                <h4>Send money</h4>
                                <p>Send money to your business pathners, friends in a short time.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End single column-->
            </div>
        </div>
    </div>
</div>
<!-- End How to area -->
<!-- Start about area -->
<div class="about-area bg-color2 area-padding">
    <div class="container">
        <div class="row">
            <!-- Start column-->
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="about-image">
                    <img src="img/about/vd.jpg" alt="" class="ab-first-img">
                    <img src="img/about/vd1.jpg" alt="" class="ab-second-img">
                    <a href="https://www.youtube.com/watch?v=O33uuBh6nXA" class="video-play vid-zone">
                        <i class="fa fa-play"></i>
                    </a>
                </div>
            </div>
            <!-- End column-->
            <!-- Start column-->
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="about-content">
                    <h3>Why choose our world fast online payment services.</h3>
                    <p class="hidden-sm">You wouldn't want to miss using our payment API</p>
                    <div class="about-details">
                        <div class="single-about">
                            <a href="#"><i class="flaticon-079-graphic"></i></a>
                            <div class="icon-text">
                                <h5>Low Costing</h5>
                                <p>Transactions costs are very small.</p>
                            </div>
                        </div>
                        <div class="single-about">
                            <a href="#"><i class="flaticon-007-document-2"></i></a>
                            <div class="icon-text">
                                <h5>Safe & Secure</h5>
                                <p>Making transactions can never be more safe and secure.</p>
                            </div>
                        </div>
                        <div class="single-about">
                            <a href="#"><i class="flaticon-107-speech-bubbles"></i></a>
                            <div class="icon-text">
                                <h5>Live Support</h5>
                                <p>In a case of any issue our live support is a click away</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End column-->
        </div>
    </div>
</div>

<!-- End about area -->
<!-- Start testimonials Area -->
<div class="reviews-page-area bg-color fix area-padding-2">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="section-headline text-center">
                    <h2>Customer Reviews</h2>
                    <p>Below are some of our customers reviews</p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="reviews-content">
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="single-testi">
                        <div class="testi-text">
                            <div class="clients-text">
                                <div class="client-rating">
                                    <a href="#"><i class="ti-star"></i></a>
                                    <a href="#"><i class="ti-star"></i></a>
                                    <a href="#"><i class="ti-star"></i></a>
                                    <a href="#"><i class="ti-star"></i></a>
                                    <a href="#"><i class="ti-star"></i></a>
                                </div>
                                <p>I have been using this bank for fours to run my business and it has been all good news.</p>
                            </div>
                            <div class="testi-img ">
                                <img src="img/review/1.jpg" alt="">
                                <div class="guest-details">
                                    <h4>Hamilton</h4>
                                    <span class="guest-rev">Clients - <a href="#">Business Owner</a></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="single-testi">
                        <div class="testi-text">
                            <div class="clients-text">
                                <div class="client-rating">
                                    <a href="#"><i class="ti-star"></i></a>
                                    <a href="#"><i class="ti-star"></i></a>
                                    <a href="#"><i class="ti-star"></i></a>
                                    <a href="#"><i class="ti-star"></i></a>
                                    <a href="#"><i class="ti-star"></i></a>
                                </div>
                                <p>For six years i have been banking with PGC I haven't experienced any downtime.</p>
                            </div>
                            <div class="testi-img ">
                                <img src="img/review/2.jpg" alt="">
                                <div class="guest-details">
                                    <h4>Angel lima</h4>
                                    <span class="guest-rev">Clients - <a href="#">Customer for 6 years</a></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- End single item -->
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="single-testi">
                        <div class="testi-text">
                            <div class="clients-text">
                                <div class="client-rating">
                                    <a href="#"><i class="ti-star"></i></a>
                                    <a href="#"><i class="ti-star"></i></a>
                                    <a href="#"><i class="ti-star"></i></a>
                                    <a href="#"><i class="ti-star"></i></a>
                                    <a href="#"><i class="ti-star"></i></a>
                                </div>
                                <p>20th May marked it 4 years I have been using PGC bank plc</p>
                            </div>
                            <div class="testi-img ">
                                <img src="img/review/3.jpg" alt="">
                                <div class="guest-details">
                                    <h4>Arthur Doil</h4>
                                    <span class="guest-rev">Clients - <a href="#">Happy Customer</a></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                <!-- End single item -->
            </div>
        </div>
    </div>
</div>
<!-- End testimonials end -->
<!-- Start overview Area -->
<div class="overview-area bg-color2 fix area-padding">
    <div class="container">
        <div class="row">
            <!-- Start column-->
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="overview-content">
                    <div class="overview-images">
                        <img src="img/about/overview.jpg" alt="">
                    </div>
                </div>
            </div>
            <!-- End column-->
            <!-- Start column-->
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="overview-text">
                    <h3>Secure online shopping world top brand product </h3>
                    @*<p></p>*@
                    <ul>
                        <li><a href="#">Innovation idea latest business tecnology</a></li>
                        <li><a href="#">Digital content marketing online clients plateform</a></li>
                        <li><a href="#">Safe secure services for you online email account</a></li>
                    </ul>
                    <a class="overview-btn" asp-page="/Register">Signup today</a>
                </div>
            </div>
            <!-- End column-->
        </div>
    </div>
</div>
<!-- End overview area -->
<!-- Start apps download area -->
<div class="download-area bg-color2 area-padding">
<div class="container">
    <div class="row">
        <!-- Start column -->
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="download-text">
                <h3>Very soon you can Download our apps on all the various app stores.</h3>
                <p>Our mobile apps are still under development but will soon be available</p>
                <div class="down-btn" data-wow-delay="0.7s">
                    <a href="#" class="app-btn left-btn">Play store</a>
                    <a href="#" class="app-btn right-btn">App store</a>
                </div>
            </div>
        </div>
        <!-- End column -->
        <!-- Start column -->
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="download-image">
                <img src="img/about/download.jpg" alt="download-image">
            </div>
        </div>
        <!-- End column -->
    </div>
</div>
</div>
<!-- End apps download area -->

Bank/Pages/Logout.cshtml
@page
@model Bank.Pages.Account.LogoutModel
@{
}
<!-- Start breadcrumbs area -->
<div class="page-area">
    <div class="breadcumb-overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="breadcrumb text-center">
                    <div class="section-headline white-headline text-center">
                        <h3>LogOut</h3>
                    </div>

                    <form method="post">
                        <div class="container mt-5">
                            <div class="row justify-content-center">
                                <div class="col-sm-12 col-lg-4 col-md-12">
                                    <h4>Are You Sure You Want To Logout?</h4>

                                    <p>
                                        <button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
                                        <button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">No</button>
                                    </p>
                                </div>
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
<!-- End breadcrumbs area -->

Bank/Pages/Update.cshtml
@page
@model Bank.Pages.UpdateModel
@{
}